DvdLibrary/Models/Dvd.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DvdLibrary.Models
{
    public class Dvd
    {
        public int DvdID { get; set; }
        public string Title { get; set; }
        public string ReleaseYear { get; set; }
        public string Director { get; set; }
        public string Rating { get; set; }
        public string Notes { get; set; }
    }
}

DvdLibrary/Controllers/DVDController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Http.Cors;
using System.Web.Mvc;
using DvdLibrary.Interfaces;
using DvdLibrary.Models;
using DvdLibrary.Repositories;

namespace DvdLibrary.Controllers
{
    [EnableCors(origins: "*", headers: "*", methods: "*")]
    public class DVDController : Controller
    {
        private IDVDRepository db = DVDLibraryRepositoryFactory.CreateDvdRepository();
        
        [HttpGet]
        public ActionResult List()
        {
            return View(db.GetAll());
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            return View(db.GetByID(id));
        }

        [HttpGet]
        public ActionResult GetByTitle(string searchText)
        {
            return View("List", db.GetByTitle(searchText));
        }

        [HttpGet]
        public ActionResult GetByReleaseYear(string searchText)
        {
            return View("List", db.GetByReleaseYear(searchText));
        }

        [HttpGet]
        public ActionResult GetByDirector(string searchText)
        {
            return View("List", db.GetByDirector(searchText));
        }

        [HttpGet]
        public ActionResult GetByRating(string searchText)
        {
            return View("List", db.GetByRating(searchText));
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            return View(db.GetByID(id));
        }

        [HttpPost]
        public ActionResult Edit(Dvd dvd)
        {
            db.Update(dvd);
            return View(db.GetByID(dvd.DvdID));
        }

        [HttpGet]
        public ActionResult Create()
        {
            Dvd dvd = new Dvd();
            return View(dvd);
        }

        [HttpPost]
        public ActionResult Create(Dvd dvd)
        {
            dvd.DvdID = db.Create(dvd);
            return View("Details", dvd);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            return View(db.GetByID(id));
        }

        public ActionResult DeleteDVD(int id)
        {
            db.Delete(id);
            return View("List", db.GetAll());
        }
    }
}

DvdLibrary/Views/DVD/Create.cshtml
@model DvdLibrary.Models.Dvd

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Dvd</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseYear, new { htmlAttributes = new { @class = "form-control", @type = "number" } })
                @Html.ValidationMessageFor(model => model.ReleaseYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Director, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Director, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Director, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DvdLibrary/Views/DVD/Delete.cshtml
@model DvdLibrary.Models.Dvd

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Dvd</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Director)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Director)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.ActionLink("Delete", "DeleteDVD", new { id =  Model.DvdID }) |
            @Html.ActionLink("Back to List", "List")
        </div>
    }
</div>

DvdLibrary/Views/DVD/Details.cshtml
@model DvdLibrary.Models.Dvd

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Dvd</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Director)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Director)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.DvdID }) |
    @Html.ActionLink("Back to List", "List")
</p>

DvdLibrary/Views/DVD/Edit.cshtml
@model DvdLibrary.Models.Dvd

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Dvd</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DvdID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseYear, new { htmlAttributes = new { @class = "form-control", @type = "number"} })
                @Html.ValidationMessageFor(model => model.ReleaseYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Director, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Director, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Director, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DvdLibrary/Views/DVD/List.cshtml
@model IEnumerable<DvdLibrary.Models.Dvd>

@{
    ViewBag.Title = "List";
    List<SelectListItem> searchTerms = new List<SelectListItem>();
    searchTerms.Add(new SelectListItem() { Text = "Title", Value = "1" });
    searchTerms.Add(new SelectListItem() { Text = "Release Year", Value = "2" });
    searchTerms.Add(new SelectListItem() { Text = "Director", Value = "3" });
    searchTerms.Add(new SelectListItem() { Text = "Rating", Value = "4" });
}

<h2>List</h2>

<p>
    @Html.ActionLink("Create New", "Create") @Html.DropDownList("Search Term", searchTerms, new { id = "searchTerm" }) <input type="text" id="searchText" placeholder="Search"/> <button type="button" onclick="Search()">Search</button>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReleaseYear)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Director)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rating)
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.Title, "Details", new { id = item.DvdID })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReleaseYear)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Director)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rating)
        </td>

        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.DvdID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.DvdID })
        </td>
    </tr>
}

</table>
<script>
    function Search(e) {
        //e.preventDefault();
        var url = '';
        var searchText = $('#searchText').val();

        if (!searchText) {
            return;
        }

        switch ($('#searchTerm').val()) {
            case "2":
                url += '@Url.Action("GetByReleaseYear", "DVD")' + '?searchText=' + searchText;
                break;
            case "3":
                url += '@Url.Action("GetByDirector", "DVD")' + '?searchText=' + searchText;
                break;
            case "4":
                url += '@Url.Action("GetByRating", "DVD")' + '?searchText=' + searchText;
                break;
            default:
                url += '@Url.Action("GetByTitle", "DVD")' + '?searchText=' + searchText;
                break;
        }

        window.location = url;
    }
</script>